name: Build Docker Image for Dockerhub

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: "0 0 1 1/3 *"

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Updates Checkout
      uses: actions/checkout@v3

    - name: Docker Login
      env:
        USERNAME: ${{ secrets.DOCKER_USERNAME }}
        PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: |
        docker login -u $USERNAME -p $PASSWORD

    - name: Build the Docker Image
      run: docker build . --file Dockerfile --tag modern-crypto:$(date +%s) --tag modern-crypto:latest
    
    - name: Push to Dockerhub
      run: docker push docker.io/${{ secrets.DOCKER_USERNAME }}/modern-crypto:latest
