name: Docker Image for GitHub packages

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout Updates
      uses: actions/checkout@v3
    
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag ghcr.io/ravi-prakash1907/modern-crypto:$(date +%s) --tag ghcr.io/ravi-prakash1907/modern-crypto:latest
    
    - name: Push to Dockerhub
      run: docker push ghcr.io/ravi-prakash1907/modern-crypto:latest
