name: Docker Image for GitHub packages

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout Updates
      uses: actions/checkout@v3
    
    - name: Build the Docker image
      run: docker build . --file Dockerfile --build-arg GET_CACHED_MOD=false --tag modern-crypto:$(date +%s) --tag modern-crypto:latest
